# Generated by Django 5.2.15 on 2026-07-12 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion_apertura', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('saldo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_teorico_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacion_cierre', models.TextField(blank=True)),
                ('resumen_cierre', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('propietaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-abierta_en',),
            },
        ),
        migrations.CreateModel(
            name='GastoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('anulado', 'Anulado')], default='registrado', max_length=20)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_caja_anulados', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='caja.caja')),
            ],
            options={
                'ordering': ('-registrado_en',),
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aporte', 'Aporte'), ('retiro', 'Retiro')], max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('anulado', 'Anulado')], default='registrado', max_length=20)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_anulados', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.caja')),
            ],
            options={
                'ordering': ('-registrado_en',),
            },
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['propietaria', 'estado'], name='caja_caja_propiet_793e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['propietaria', 'abierta_en'], name='caja_caja_propiet_e515ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_inicial__gte', 0)), name='caja_saldo_inicial_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('propietaria',), name='caja_una_abierta_por_propietaria'),
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['caja', 'estado'], name='caja_gastoc_caja_id_dec499_idx'),
        ),
        migrations.AddConstraint(
            model_name='gastocaja',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='gasto_caja_importe_positivo'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['caja', 'estado'], name='caja_movimi_caja_id_a06559_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='movimiento_caja_importe_positivo'),
        ),
    ]
