# Generated by Django 5.2.15 on 2026-07-11 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=120, verbose_name='apellido')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('color_favorito', models.CharField(blank=True, max_length=80, verbose_name='color favorito')),
                ('estilo_favorito', models.CharField(blank=True, max_length=120, verbose_name='estilo favorito')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='actualizada en')),
                ('propietaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientas', to=settings.AUTH_USER_MODEL, verbose_name='propietaria')),
            ],
            options={
                'verbose_name': 'clienta',
                'verbose_name_plural': 'clientas',
                'ordering': ('-activa', 'nombre', 'apellido'),
            },
        ),
    ]
