# Generated by Django 5.2.15 on 2026-07-12 20:18

from django.conf import settings
from django.db import migrations, models
import re


def normalizar_email(value):
    return value.strip().lower()


def normalizar_telefono(value):
    return re.sub(r"\D+", "", value)


def completar_claves_normalizadas(apps, schema_editor):
    Clienta = apps.get_model("clientas", "Clienta")
    clientas = list(Clienta.objects.all().only("id", "propietaria_id", "email", "telefono"))
    cantidad_emails = {}
    cantidad_telefonos = {}
    claves = {}

    for clienta in clientas:
        email = normalizar_email(clienta.email)
        telefono = normalizar_telefono(clienta.telefono)
        claves[clienta.id] = (email, telefono)
        if email:
            clave_email = (clienta.propietaria_id, email)
            cantidad_emails[clave_email] = cantidad_emails.get(clave_email, 0) + 1
        if telefono:
            clave_telefono = (clienta.propietaria_id, telefono)
            cantidad_telefonos[clave_telefono] = cantidad_telefonos.get(clave_telefono, 0) + 1

    for clienta in clientas:
        email, telefono = claves[clienta.id]
        email_normalizado = email if email and cantidad_emails[(clienta.propietaria_id, email)] == 1 else ""
        telefono_normalizado = telefono if telefono and cantidad_telefonos[(clienta.propietaria_id, telefono)] == 1 else ""
        Clienta.objects.filter(pk=clienta.pk).update(
            email_normalizado=email_normalizado,
            telefono_normalizado=telefono_normalizado,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clientas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clienta',
            name='email_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='clienta',
            name='telefono_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.RunPython(completar_claves_normalizadas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='clienta',
            constraint=models.UniqueConstraint(condition=models.Q(('email_normalizado__gt', '')), fields=('propietaria', 'email_normalizado'), name='clientas_email_normalizado_unico_por_propietaria'),
        ),
        migrations.AddConstraint(
            model_name='clienta',
            constraint=models.UniqueConstraint(condition=models.Q(('telefono_normalizado__gt', '')), fields=('propietaria', 'telefono_normalizado'), name='clientas_telefono_normalizado_unico_por_propietaria'),
        ),
    ]
