import { useEffect, useState } from "react";
import { Link, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { getServicio, estadoServicio, listServicios, saveServicio } from "../api/servicios.js";
import AppHeader from "../components/AppHeader.jsx";
const money=(v)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(v); const initial={nombre:"",descripcion:"",duracion_minutos:"60",precio:"",orden:"0"};
function Page({children}){return <main className="min-h-screen bg-[#fff8f7] text-[#3d2f32]"><AppHeader/><section className="mx-auto max-w-4xl px-5 py-8">{children}</section></main>}
function List(){const [items,setItems]=useState([]),[search,setSearch]=useState(""),[estado,setEstado]=useState("activos"),[error,setError]=useState("");useEffect(()=>{listServicios({search,estado}).then(setItems).catch(()=>setError("No pudimos cargar tus servicios."));},[search,estado]);const empty=search?"No encontramos servicios con esa búsqueda.":estado==="pausados"?"No tenés servicios pausados.":"Todavía no agregaste ningún servicio.";return <Page><div className="flex justify-between"><h1 className="text-3xl font-semibold">Mis servicios</h1><Link className="rounded-xl bg-[#b76e79] px-4 py-3 font-semibold text-white" to="nuevo">Nuevo servicio</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><input className="rounded-xl border p-3" placeholder="Buscar servicios" value={search} onChange={e=>setSearch(e.target.value)}/><select className="rounded-xl border p-3" value={estado} onChange={e=>setEstado(e.target.value)}><option value="activos">Activos</option><option value="pausados">Pausados</option><option value="todos">Todos</option></select></div>{error&&<p className="mt-5 text-[#8b3f4c]">{error}</p>}<div className="mt-6 grid gap-3">{items.map(s=><Link className="rounded-2xl border bg-white p-5" to={`${s.id}`} key={s.id}><b>{s.nombre}</b><p className="mt-1 text-sm text-[#6f5b60]">{s.duracion_legible} · {money(s.precio)} {!s.activo&&"· Pausado"}</p></Link>)}{!error&&!items.length&&<p className="rounded-2xl border bg-white p-8 text-center">{empty}</p>}</div></Page>}
function Form(){const{id}=useParams(),nav=useNavigate(),[v,setV]=useState(initial),[err,setErr]=useState("");useEffect(()=>{if(id)getServicio(id).then(setV).catch(()=>setErr("No encontramos este servicio."));},[id]);const submit=async e=>{e.preventDefault();try{const s=await saveServicio(id,{...v,duracion_minutos:Number(v.duracion_minutos),orden:Number(v.orden)});nav(`/servicios/${s.id}`)}catch(x){setErr(x.response?.data?.nombre?.[0]||x.response?.data?.duracion_minutos?.[0]||x.response?.data?.precio?.[0]||"Revisá los campos marcados.")}};return <Page><Link to="/servicios">Volver</Link><h1 className="mt-4 text-3xl font-semibold">{id?"Editar servicio":"Nuevo servicio"}</h1><form className="mt-6 space-y-4 rounded-2xl border bg-white p-6" onSubmit={submit}>{[["nombre","Nombre","text"],["descripcion","Descripción","text"],["duracion_minutos","Duración estimada (minutos)","number"],["precio","Precio en pesos argentinos","number"],["orden","Orden visual","number"]].map(([n,l,t])=><label className="block" key={n}>{l}<input required={n!=="descripcion"} min={t==="number"?"0":undefined} step={n==="precio"?"0.01":"1"} className="mt-1 w-full rounded-xl border p-3" type={t} value={v[n]??""} onChange={e=>setV({...v,[n]:e.target.value})}/></label>)}<p className="text-sm text-[#6f5b60]">Ejemplo: 90 minutos equivale a 1 h 30 min.</p>{err&&<p className="text-[#8b3f4c]">{err}</p>}<button className="rounded-xl bg-[#b76e79] px-5 py-3 font-semibold text-white">{id?"Guardar cambios":"Guardar servicio"}</button></form></Page>}
function Detail(){const{id}=useParams(),[s,setS]=useState(null),[err,setErr]=useState("");useEffect(()=>{getServicio(id).then(setS).catch(()=>setErr("No encontramos este servicio."));},[id]);const change=async()=>{if(s.activo&&!window.confirm("El servicio dejará de aparecer entre los activos, pero conservarás toda su información."))return;try{setS(await estadoServicio(id,!s.activo))}catch{setErr("No pudimos actualizar el servicio.")}};if(err)return <Page><p>{err}</p></Page>;if(!s)return <Page><p>Cargando servicio...</p></Page>;return <Page><Link to="/servicios">Volver a mis servicios</Link><div className="mt-5 rounded-2xl border bg-white p-6"><h1 className="text-3xl font-semibold">{s.nombre}</h1><p>{s.activo?"Activo":"Pausado"}</p><p className="mt-5">{s.descripcion||"Sin descripción."}</p><p>{s.duracion_legible} · {money(s.precio)}</p><p>Orden visual: {s.orden}</p><Link className="mt-6 inline-block font-semibold underline" to="editar">Editar</Link><button className="ml-5 rounded-xl border px-4 py-2" onClick={change}>{s.activo?"Pausar":"Reactivar"}</button></div></Page>}
export default function ServiciosPage(){return <Routes><Route index element={<List/>}/><Route path="nuevo" element={<Form/>}/><Route path=":id" element={<Detail/>}/><Route path=":id/editar" element={<Form/>}/></Routes>}
