# Generated by Django 5.2.15 on 2026-07-11 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0003_alter_turno_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clienta_nombre_historica', models.CharField(max_length=241)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('detalle_metodo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('anulado', 'Anulado')], default='registrado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_anulados', to=settings.AUTH_USER_MODEL)),
                ('propietaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='turnos.turno')),
            ],
            options={
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['propietaria', 'creado_en'], name='cobros_cobr_propiet_0d46ee_idx'), models.Index(fields=['propietaria', 'estado'], name='cobros_cobr_propiet_7cbe43_idx'), models.Index(fields=['turno'], name='cobros_cobr_turno_i_a9c44c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='cobros_importe_positivo'), models.UniqueConstraint(condition=models.Q(('estado', 'registrado')), fields=('turno',), name='cobros_un_registrado_por_turno')],
            },
        ),
    ]
