# Generated by Django 5.2.15 on 2026-07-11 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientas', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('reprogramado', 'Reprogramado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('duracion_total_minutos', models.PositiveIntegerField()),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='clientas.clienta')),
                ('propietaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('inicio',),
            },
        ),
        migrations.CreateModel(
            name='TurnoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=120)),
                ('duracion_minutos', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_historicos', to='servicios.servicio')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_servicios', to='turnos.turno')),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
    ]
