# Generated by Django 5.2.15 on 2026-07-11 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientas', '0001_initial'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['propietaria', 'inicio'], name='turnos_turn_propiet_56eec1_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['propietaria', 'estado'], name='turnos_turn_propiet_31c5fd_idx'),
        ),
    ]
