# Generated by Django 5.2.15 on 2026-07-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_turnos_turn_propiet_56eec1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('reprogramado', 'Reprogramado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado'), ('no_vino', 'No vino')], default='pendiente', max_length=20),
        ),
    ]
